Add function for accounting of debt due to delegation
trustlines-protocol/contracts pull request #239
Opened 2019-09-03 15:10 UTC by cducrest

closes https://github.com/trustlines-protocol/contracts/issues/238

2019-09-09 07:46 UTC, ghost requested changes
I don't understand how increaseDebt is going to be used. Please add a comment that explains it.

2019-09-09 11:05 UTC, cducrest commented
> I don't understand how increaseDebt is going to be used. Please add a comment that explains it.

Done

2019-09-09 11:28 UTC, schmir-at-bb commented
> > I don't understand how increaseDebt is going to be used. Please add a comment that explains it.
> 
> Done

I think the crucial information is that this is going to be called from the identity contract. That information is still missing.

2019-09-09 11:29 UTC, ghost approved these changes

2019-09-09 18:16 UTC, berndbohmeier requested changes
Please lets have a short discussion about this tomorrow.

2019-09-10 09:04 UTC, berndbohmeier commented on contracts/CurrencyNetwork.sol
> +            debt[uniqueIdentifier(debtor, creditor)] -= value;
```suggestion
            debt[uniqueIdentifier(debtor, creditor)] = newDept;
```

2019-09-10 13:34 UTC, berndbohmeier approved these changes

2019-09-10 13:35 UTC, berndbohmeier commented
I would not document how it will be used. But we should probably later document how the tracked debt can be redeemed.

2019-09-10 14:03 UTC, schmir-at-bb commented
> I would not document how it will be used, as this is the wrong direction of thinking and creates an additional dependency. But we should probably later document how the tracked debt can be redeemed.

Well, the function is there and there's a reason for the existence of that function. Why would any sane person call a function called increaseDebt, when it's your own debt that's increasing? I think that's rather surprising and deserves some clarification.

2019-09-10 14:55 UTC, berndbohmeier commented
Yeah, but this is just one usecase. It is in general there to be able to have a a debt claim for trustlines money. 
I feel like you could do the same argumentation for a transfer, why should a sane person do a transfer when then the other person receives the money.

2019-09-10 14:57 UTC, berndbohmeier commented
We can document it as `Provides a way to pay someone if there is no trustlines path yet. The claim can be redeemed later if there exists a path then`

Would that work for you?

2019-09-10 20:50 UTC, schmir-at-bb commented
>  I feel like you could do the same argumentation for a transfer, why should a sane person do a transfer when then the other person receives the money.

That's right. Yet, it's still confusing to me, even more so because I'm making up bogus arguments. Just let me not think about it by telling my why it's here and how it's being used.

> Provides a way to pay someone if there is no trustlines path yet. The claim can be redeemed later if there exists a path then

That's ok, though I still do think it wouldn't hurt to say it was introduced to pay delegates via calls from the identity contract.

2019-09-11 12:50 UTC, closed without merging